### ISSUE TITLE
Artifacts Stats migration from source Artifactory to destination artifactory

### ISSUE THREAD

**Issue by nyadav08** [jfrog/docker2artifactory#7]
Hi,

It appears when you have an Artifactory as a source this tool doesn't migrate any artifactory stats. I have following question/issues to ask.

1. Is it possible to also migrate stats when source is an Artifactory?
2. Does this tool only migrate the images/tags, which doesn't exist on destination? I am wondering if we populate all the stats by export/import and after that we run the migrator then whether it will wipe out all the stats or stats will stay as is because its in DB already existed.

Thanks for your reply.

**Comment by jfrog-aparicio** [comment]
Closing as this is outside the scope of this tool.  This may be better with replication/REST API or export/import features of Artifactory.
