### ISSUE TITLE
Artifactory _upload files causes mismatch of source and target layers

### ISSUE THREAD

**Issue by jerryb01** [jfrog/docker2artifactory#8]
Layers out of sync when migrating docker image artifactory to artifactory instance using generic registry

Steps to reproduce:
source instance has an image-a with a new tag or missing tag from the target image
target instance has the image-a with some tags and orphan layers exist in _uploads folder
migrator creates the missing tag in the target but target layers do not match the source

workaround: delete the _uploads folder on the target, delete the new out of sync tag, re-run DockerMigrator

**Comment by jfrog-aparicio** [comment]
Sorry for the long delay on this. I ran this test on 6.9.1 but am not able to reproduce it:

1. Create 2 tags for the same image in source
2. Upload 1 of the 2 tags to the target
3. Upload a large tag of the same image name but different contents to target, killing it before it completes (this leaves the _uploads directory with the layers that made it before being killed).
4. Run the migrator

The results were the two expected images in the target after running the migrator.

Please feel free to reopen it if you are still seeing this and specify the version of Artifactory.
