### ISSUE TITLE
DockerMigrator.py generic fails at checking Artifactory version

### ISSUE THREAD

**Issue by Kyslik** [jfrog/docker2artifactory#9]
I hope this verbose output is enough:

```sh
[MainThread] [INFO] (migrator.ArtifactoryBaseAccess:124) - Sending GET request to REDACTED.jfrog.io/api/system/version.
[MainThread] [INFO] (migrator.ArtifactoryBaseAccess:44) - Exception caught when executing get request: unknown url type: REDACTED.jfrog.io/api/system/version
[MainThread] [ERROR] (migrator.ArtifactoryBaseAccess:40) - The server does not appear to be an Artifactory instance or is not replying as expected.
```

This line seems to cause the problem.

https://github.com/jfrog/docker2artifactory/blob/c18d1e209c0f995806cd9c54ed20641eeac79a2f/migrator/ArtifactoryBaseAccess.py#L36

**Comment by jfrog-aparicio** [comment]
Hello,

It looks like you may be trying it without the Artifactory context. Can you try it again, this time providing the Artifactory URL as:

<servername>.jfrog.io/<servername>
Instead of:
<servername>.jfrog.io

**Comment by ladislav-kosco-dragon** [comment]
Well, we passed this part, as we created some docker repository, and after some debugging we got around this path.
this is because when creating local docker registry, it created some 
`<veeeeeeeeery-long-name>`.jfrog.io
but API is accessible under 
`<veeeeeeeeery-long-name>`.jfrog.io/`<project name>`

and now we face issue of local docker repository detection
```sh
[MainThread] [INFO] (migrator.DockerRegistryAccess:52) - Verify Registry is V2
[MainThread] [INFO] (migrator.HTTPAccess:124) - Sending GET request to https://REDACTED.amazonaws.com/REDACTED/v2/.
[MainThread] [INFO] (migrator.ArtifactoryBaseAccess:35) - Checking the Artifatory version
[MainThread] [INFO] (migrator.ArtifactoryBaseAccess:124) - Sending GET request to https://REDACTED.jfrog.io/REDACTED/api/system/version.
[MainThread] [INFO] (migrator.ArtifactoryBaseAccess:40) - Found version: 6.11.3
[MainThread] [INFO] (migrator.ArtifactoryDockerAccess:133) - Checking the Artifatory Docker repo 'docker-ecr-artifactory-mirror-test'
[MainThread] [INFO] (migrator.ArtifactoryDockerAccess:124) - Sending GET request to https://REDACTED.jfrog.io/REDACTED/api/repositories/docker-ecr-artifactory-mirror-test.
The repo docker-ecr-artifactory-mirror-test does not appear to be a valid V2 Docker repository.
```

and checking the output of the url on last line returns
```json
{
  "key" : "docker-ecr-artifactory-mirror-test",
  "packageType" : "docker",
  "description" : "",
  "rclass" : "local"
}
```

did we missed anything in setting up docker registry in Artifactory?

**Comment by jfrog-aparicio** [comment]
Are you using an administrator account to perform this? If not, you should be using an admin account.

**Comment by ladislav-kosco-dragon** [comment]
we are not using admin account, it has too broad rights, we actually managed to get this working by changing check for dockerApiVersion
```diff
diff --git a/migrator/ArtifactoryDockerAccess.py b/migrator/ArtifactoryDockerAccess.py
index dccd88c..17a8b22 100644
--- a/migrator/ArtifactoryDockerAccess.py
+++ b/migrator/ArtifactoryDockerAccess.py
@@ -133,8 +133,12 @@ class ArtifactoryDockerAccess(ArtifactoryBaseAccess):
         self.log.info("Checking the Artifatory Docker repo '%s'" % self.repo)
         msg = self.get_call_wrapper("/api/repositories/%s" % self.repo)
         if msg and 'packageType' in msg and msg['packageType'] == 'docker':
+            return True
+        '''
+        only admin sees this crap
             if 'dockerApiVersion' in msg and msg['dockerApiVersion'] == "V2":
                 return True
+        '''
         return False
 
     '''
```

is there any other need for admin rights we do not see now, or is it just artifactory not reporting `dockerApiVersion` for non-admins? if it is the second case, it might be better to ask for enhancement at artifacory side to provide this information to non-administrators.

**Comment by jfrog-aparicio** [comment]
For importing images, you should be fine with a non-admin for everything other than that check. If you were using it to import users/permissions/groups from select Docker registries (DTR, Quay), you would need and admin.

Did the import ultimately work?

**Comment by ladislav-kosco-dragon** [comment]
The testing ecr definitely worked. I do hope the real ecr will not have
permission issues you mentioned. Is there a way to modify code maybe add a
flag to avoid admin rights and pass expected version to program?

**Comment by jfrog-aparicio** [comment]
I have added an additional check (https://github.com/jfrog/docker2artifactory/commit/371a55808fa482c81d1e7a8b28ce3dd369b1767e) if the first fails. The new check should work for non-administrators.
